Traceback (most recent call last):
  File "test.py", line 13, in <module>
    sqlite_cursor.execute("SELECT * FROM table_name")
sqlite3.OperationalError: no such table: table_name
