2024-10-23 08:40:13
Get TypeError("'<' not supported between instances of 'str' and 'datetime.datetime'") in valid_func for name:"aut_key"


